### ISSUE TITLE
ThirdPartyEmailPassword not found

### ISSUE THREAD

**Issue by CodeTriager** [supertokens/supertokens-web-js#75] opened 2022-12-19 11:48 UTC
I'm trying to create my own login screen for an angular application. If I use the tsx file with the default login it works. When I try to do a custom UI and follow the guide right here (https://supertokens.com/docs/thirdpartyemailpassword/custom-ui/email-password-login) I get the following Error:

`error Error: No instance of ThirdPartyEmailPassword found. Make sure to call the ThirdPartyEmailPassword.init method.`

When I try to import the xxx like described here (https://supertokens.com/docs/auth-react/0.14.X/thirdpartyemailpassword/init) I still get the same error.

My app.component.ts looks like the following:

`import { Component } from '@angular/core';

// import * as SuperTokens from "supertokens-auth-react";
import SuperTokens from "supertokens-auth-react";
import Session from "supertokens-auth-react/recipe/session";
// import * as ThirdPartyEmailPassword  from "supertokens-auth-react/recipe/thirdpartyemailpassword";
import ThirdPartyEmailPassword from "supertokens-auth-react/recipe/thirdpartyemailpassword";
import EmailPassword from 'supertokens-auth-react/lib/build/recipe/emailpassword/recipe';

SuperTokens.init({
  appInfo: {
    appName: "frontend",
    apiDomain: "http://localhost:8080",
    websiteDomain: "http://localhost:4200",
    apiBasePath: "/auth",
    websiteBasePath: "/auth"
  },
  recipeList: [
    ThirdPartyEmailPassword.init({}),
    Session.init()
    ],
});

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'frontend';
}`

**Comment by rishabhpoddar** [comment] 2022-12-25 11:08
hey @CodeTriager thanks for raising this issue. @alisher-aituarov will have a look at this

**Comment by alisher-aituarov** [comment] 2022-12-26 13:27
> hey @CodeTriager thanks for raising this issue. @alisher-aituarov will have a look at this

hey! Since you are going with custom UI you want to import things from supertokens-web-js 
`import * as SuperTokens from "supertokens-web-js";`
`import * as ThirdPartyEmailPassword from "supertokens-web-js/recipe/thirdpartyemailpassword";`

**Comment by rishabhpoddar** [comment] 2022-12-26 13:40
Since you are initialising supertokens-auth-react, you want to import from `supertokens-auth-react` in your UI logic and not from `supertokens-web-js`.

**Comment by rishabhpoddar** [comment] 2022-12-26 13:40
The custom UI docs says to import from web-js, but just change those imports to point to supertokens-auth-react instead.

**Comment by rishabhpoddar** [comment] 2022-12-26 13:41
Alternatively, you can use supertokens-web-js everywhere but then you would also have to initialise the supertokens-web-js SDK and not the supertokens-auth-react SDK (this is what @alisher-aituarov was trying to say above).

Anyhow, since this is not a bug in supertokens, Im closing this issue for now

**Closed by rishabhpoddar** 2022-12-26 13:41 UTC

**Comment by CodeTriager** [comment] 2022-12-26 13:51
Thank you for your help! I changed all imports to the webjs implementation and it now works! Was a bit confusing with the different documentations
